### ISSUE TITLE
Localized form for Cyrillic should be expanded

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [alerque/libertinus#29]
Here is a test for localized form for Cyrillic:
![1](https://i.imgur.com/tNpHl8N.png)
![2](https://i.imgur.com/KkBnoDm.png)
In this case б should be transformed in all faces, other letters should also has italic variant in Libertinus Serif Italic, Libertinus Serif Bold Italic and so on. BTW I found [Bosnian](https://en.wikipedia.org/wiki/Bosnian_language) sometimes uses Serbian Cyrillic in Bosnia and Herzegovina, is it possible to make it available for Bosnian?

**Comment by Crissov** [comment]
If I understand correctly, the issue is that most southern Slavic writing systems share the same glyph variants, but they are currently only defined in `locl` for certain language codes (e.g. Serbian). Although I agree that this should be fixed at some point, I think it’s also what [`font-language-override`](http://www.w3.org/TR/css-fonts-3/#font-language-override-prop) is intended for in CSS.

**Comment by KrasnayaPloshchad** [comment]
In this case _ѓ_ should also transformed as _ī́_ in all italic faces for southern Slavonics.

**Comment by khaledhosny** [comment]
So the original report is very short in details, and I still don’t know what is being requested here.

I need simple points that can be easily understood by a non-native, e.g. character U+XXXX should use glyph foo for locales X, Y and Z.

**Comment by Crissov** [comment]
I will update [my JSFiddle](https://jsfiddle.net/3se3dpnz) soon.

**Comment by KrasnayaPloshchad** [comment]
Let me explain what happened to me.

The following characters should have their localized glyph for southern Slavics:
U+0431 (б) — should looks like δ in all faces.
U+0433 (г) — should transformed as _ī_ in any italic faces.
U+0453 (ѓ) — should transformed as _ī́_ in any italic faces.
U+0433 (д) — should transformed as _ɡ_ in any italic faces.
U+043F (п) — should transformed as _ū_ in any italic faces.
U+0442 (т) — should transformed as _ɯ̅_ in any italic faces.

When I made the test on wymeditor.github.io, the results to me as follows:
Libertinus Serif: only б, г, д, п, т works in Serbian.
Libertinus Sans: no localized glyph appearing.

**Comment by khaledhosny** [comment]
OK, any samples from fonts doing this right? Is there a definitive list of languages that need this behavior?

**Comment by moyogo** [comment]
@khaledhosny this is a common practice for some foundries.
See http://jankojs.tripod.com/SerbianCyr.htm

Serbian and Macedonian have a preferred upright б and preferred italic б, г, д, п, т.
Additionally Macedonian has a preferred italic ѓ, but this one seems to be an omission bug in several fonts supporting the other preferred glyphs (for example Ubuntu, see https://bugs.launchpad.net/ubuntu-font-family/+bug/823276, Whitney, see, http://www.typography.com/fonts/whitney/features/whitney-language-support, Segoe UI, etc). Bosnian is usually not in the languages using the locl feature in these fonts but it makes sense it should be seeing @KrasnayaPloshchad’s comment.

@KrasnayaPloshchad What about Montenegrin?

**Comment by moyogo** [comment]
@KrasnayaPloshchad BTW according to the Ubuntu bug report, when in Macedonian, U+0433 (г) and U+0453 (ѓ) should not look like ī and ī́.

**Comment by KrasnayaPloshchad** [comment]
@moyogo I have seen another sample on this:
https://en.wikipedia.org/wiki/File:Macedonian_cursive_script.svg

**Comment by KrasnayaPloshchad** [comment]
> What about Montenegrin?

I have no idea about Montenegrin, because I know nothing about that.

**Comment by landswellsong** [comment]
@moyogo Montenegrin only gained a language status this year and their language was defined as "Serbian" by the Constitution. Since they are moving away from Cyrillics anyway I think it's a safe bet that it's identical with Serbian in typography, although they introduced 2 new letters, which is other issue though.

**Comment by KrasnayaPloshchad** [comment]
> although they introduced 2 new letters, which is other issue though.

See #17

**Comment by KrasnayaPloshchad** [comment]
CC @StefanPeev

**Comment by StefanPeev** [comment]
At [Local Fonts](https://localfonts.eu) section [Fonts: the Importance of Localisation](https://localfonts.eu/typography-basics/fonts-the-importance-of-localisation/) L'm collecting information about localized forms in Cyrillic and Non-Cyrillic scripts. I hope this place will be helpful as a reference guide.

**Comment by skef** [comment]
This is *almost* resolved. U+0431 is now transformed in all main fonts, Serif and Sans. U+0433, U+0434, U+043F and U+0442 are now transformed across all the italic faces. 

The script/language directive is currently:
```
 script cyrl;
     language SRB  exclude_dflt;
      lookup locl_cyrillic;
```
U+0453 would be easy enough to add. If someone could update the the issue with advise or confirmation about additional languages and the appropriate context for a transformed U+0453, this could be resolved in short order. 

The top of the alternate U-0433 in Sans is based on a number of glyphs but not directly derived from any, so it may not reflect what the original designer's would have done. The other glyphs have direct counter-parts. Most of the Serif-SemiboldItalic glyphs are wrong, but only because the other Cyrillic glyphs are wrong and they needed to match.

**Comment by khaledhosny** [comment]
Not doing anything here. People who needs this or know what exactly is needed here are free to send pull requests.

**Comment by alerque** [comment]
See also new issue #394.

**Comment by alerque** [comment]
@d125q Any chance you would be able to review this issue and speak to what exactly is left to do to fix everything that was brought up?

**Comment by Crissov** [comment]
I think Bulgarian alternates are still missing. #122

**Comment by StefanPeev** [comment]
@Crissov @KrasnayaPloshchad International Cyrillic is updated in v.7.050 of Libertinus Serif and Bulgarian Cyrillic is added to all styles. Styles are now compatible and anyone can make is many and as different styles between Regular and Bold, based on UFO Regular and UFO Bold. See [UFO section in branch Cyrillic](https://github.com/StefanPeev/libertinus/tree/cyrillic/sources/UFO).
