### ISSUE TITLE
Superscript and subscript design not inconsistent in Math font

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [alerque/libertinus#425]
**Describe the bug**
In Libertinus Math, the superscripts and subscripts not respect the design of that of Unicode superscript and subscript characters.

**Steps to reproduce**
1. Install [TexMaths](http://roland65.free.fr/texmaths/install.html) in LibreOffice
2. Install TeX Live, set minimal scheme, after installation, open TeX Live Manager to install a small number of XeTeX packages that are enough to be used by TexMaths (if you have already installed related packages, dismiss this step)
3. Open TexMaths System Configuration, set system links, set the complier as XeLaTeX
4. Click TexMaths Equations to insert codes, configure font face in Preamble, and output with XeLaTeX

**Expected vs. actual behavior**
In Libertinus Math, the superscripts and subscripts should have the same look and feel as those Unicode superscript and subscript characters.

**Screenshots / logs**
![图片](https://user-images.githubusercontent.com/10364351/104345821-b7cb8f80-5539-11eb-96e8-ed637e44382b.png)
Left: Libertinus Math, Right: _Linux Libertine G_, another variant made by @laszlonemeth
(Also look at my attachment with LibreOffice.)

**Additional context**
[C-14 U-235.zip](https://github.com/alerque/libertinus/files/5803663/C-14.U-235.zip)

**Comment by alerque** [comment]
> not respective the design

I don't know what you mean by this. The Libertinus Math layout in your screen shot looks correct to me, and I just tested it it XeLaTeX proper and got much the same result:

![image](https://user-images.githubusercontent.com/173595/104354325-17b23e00-551a-11eb-8c61-d4acb1a27cc3.png)

<details>
<summary>TeX Code</summary>

```tex
\documentclass{article}
\usepackage{libertinus-otf}
\begin{document}
\Huge
$_{6}^{14}\text{C } _{92}^{235}\text{U}$
\end{document}
```

</details>

Stacking subscripts/superscripts without using proper Math layout is not currently supported as in the Graphite example from the other side of your shot. See #410.

**Comment by RGB-es** [comment]
@KrasnayaPloshchad, you'll get that result with any Math font, not  only Libertinus. To get properly aligned left scripts you need to use additional packages, such as `mathtools`.

In the preamble: `\usepackage{mathtools}`

In the document: `$\prescript{14}{2}{\mathbf{C}}$`

**Comment by KrasnayaPloshchad** [comment]
> I don't know what you mean by this.

I corrected that, sorry. 
So OpenType Math gives limited instructions to allow customize their positioning and scale.

**Comment by alerque** [comment]
I'm sorry, but it is still not clear to me what you are referring to. What aspect of the design do you think is not being respected? Is your complaint that TeX Math aligns super/subscripts left instead of in place like your alternating up/down arrangement using Graphite? Or that the size of Math superscipts is larger? Or something else?

**Comment by KrasnayaPloshchad** [comment]
Well, I saw in OpenType math typesetting, the size and positions of subscripts and superscripts in Libertinus Math does not aligned with the what I presented with Unicode subscript and superscript characters.

**Comment by alerque** [comment]
I don't know why you would expect two completely different layout systems meant for different use cases to produce the same results. Unicode subscripts and superscripts are limited to use and would be primarily used inline with other text. Hence the appropriate alignment for that use. A true math layout engine for use in writing formulas is going to have a very different idea about how to layout text. This includes things very much outside the bounds of what a normal line of text would include.

I've compared the math layout of the sub/superscript numbers between Libertinus Math, STIX Two, and Latin Modern. All of them look about the same overall scale and placement.

I don't see a problem here. If I'm missing something feel free to explain, but it sounds to be like your expectation that non-math layout should look the same as math layout is not a reasonable expectation. Show me where/how they are ill suited for their intended tasks and maybe something could be done about that.

**Comment by Crissov** [comment]
JFTR, [CSS](https://drafts.csswg.org/css-fonts-4/#font-variant-position-prop).
