### ISSUE TITLE
Missing character: There is no є (U+0454) in font LibertinusSerif-BoldItalic.otf

### ISSUE THREAD

**Issue by imposeren** [alerque/libertinus#521]
**Describe the bug**
There is no letter "є" in the BoldItalic version of the Serif font.

**Steps to reproduce**
Just use the smaller version of "є" character with LibertinusSerif-BoldItalic.otf font

**Expected vs. actual behavior**
It's expected to have this letter in the bold-italic version of the font, but it's not available

**Additional context**
All ok for LibertinusSerif Regular, and all ok with Libertinus sans too (all shapes and serieses)

**Comment by StefanPeev** [comment]
@imposeren The problem is solved. Check PR #520 updated.

**Comment by imposeren** [comment]
@StefanPeev are you sure? I tried building it:
https://github.com/imposeren/libertinus/releases/tag/v7.052

But still getting the same issues, e.g. with word "заспокоєння"

**Comment by StefanPeev** [comment]
@imposeren Try [this version](https://github.com/StefanPeev/libertinus/releases/tag/v.75)

**Comment by StefanPeev** [comment]
@imposeren What do you think about Libertinus Serif v.7.052 ?

**Comment by imposeren** [comment]
@StefanPeev This one works! Thank you very much
